SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720

ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE = 0.8  # seconds
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS

PLAYER_RADIUS = 20
PLAYER_TURN_SPEED = 300
PLAYER_MAX_SPEED = 200
PLAYER_SHOOT_SPEED = 500
PLAYER_SOOT_COOLDOWN = 0.3
PLAYER_FROM_ZERO_TO_FULLSPEED = 1 # seconds
PLAYER_FROM_FULLSPEED_TO_ZERO = 0.5 # seconds

SHOT_RADIUS = 5

def normalize(val: float, max: float, min: float = 0):
        return (val - min)/(max - min)